/* Copies the parts of three.js the simulator actually imports into vendor/, so
 * a plain static host (GitHub Pages) can serve the game with no build step.
 *
 * game.html carries an import map pointing 'three' and 'three/addons/' at these
 * files. Re-run after changing the three version or adding a new addon import:
 *
 *   npm run vendor
 *
 * examples/jsm is 23 MB; we walk the import graph and copy only what is reached.
 */
import { readFile, writeFile, mkdir, rm, copyFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const THREE = join(ROOT, 'node_modules/three');
const ADDONS_SRC = join(THREE, 'examples/jsm');
const OUT = join(ROOT, 'vendor');
const OUT_ADDONS = join(OUT, 'three/addons');

/* Entry points = every 'three/addons/*' specifier used under src/. */
const ENTRIES = [
    'objects/Sky.js',
    'postprocessing/EffectComposer.js',
    'postprocessing/OutputPass.js',
    'postprocessing/RenderPass.js',
    'postprocessing/SMAAPass.js',
    'postprocessing/ShaderPass.js',
    'postprocessing/UnrealBloomPass.js',
];

/* Statement-level only. A looser pattern happily matches quoted prose inside
 * comments and object literals and sends the walk chasing files that were never
 * imported. */
const PATTERNS = [
    /(?:^|[\s;}])import\s+(?:[\w*${}\s,]+from\s+)?['"]([^'"]+)['"]/g,
    /(?:^|[\s;}])export\s+[\w*${}\s,]+from\s+['"]([^'"]+)['"]/g,
    /\bimport\s*\(\s*['"]([^'"]+)['"]\s*\)/g,
];

function specifiersIn(source) {
    const clean = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"\\])\/\/.*$/gm, '$1');
    return PATTERNS.flatMap((re) => [...clean.matchAll(re)].map((m) => m[1]));
}

const seen = new Set();

async function walk(rel) {
    if (seen.has(rel)) return;
    seen.add(rel);

    const from = join(ADDONS_SRC, rel);
    if (!existsSync(from)) throw new Error(`missing addon: ${rel}`);

    const to = join(OUT_ADDONS, rel);
    await mkdir(dirname(to), { recursive: true });
    await copyFile(from, to);

    const source = await readFile(from, 'utf8');
    for (const spec of specifiersIn(source)) {
        /* Bare 'three' is handled by the import map. Relative specifiers are
         * addon-to-addon and have to come along. */
        if (!spec.startsWith('.')) continue;
        const next = relative(ADDONS_SRC, resolve(dirname(from), spec));
        if (next.startsWith('..')) throw new Error(`escapes jsm/: ${spec} in ${rel}`);
        await walk(next);
    }
}

const version = JSON.parse(await readFile(join(THREE, 'package.json'), 'utf8')).version;

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });
await copyFile(join(THREE, 'build/three.module.min.js'), join(OUT, 'three.module.min.js'));
for (const entry of ENTRIES) await walk(entry);

await writeFile(
    join(OUT, 'README.md'),
    `# vendor/\n\nGenerated by \`npm run vendor\` — do not edit by hand.\n\n` +
    `three r${version}, plus the ${seen.size} addon files reachable from the\n` +
    `simulator's imports. Served directly to the browser via the import map in\n` +
    `\`game.html\` so GitHub Pages needs no build step.\n`,
);

console.log(`vendored three r${version} + ${seen.size} addon files -> vendor/`);
